@BASE_URL=http://localhost:3000/api/sehirler
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OSJ9.P0eJNyzc0FW9Fq2cB7WxRsRLN4FzyTp1Qs0CWHQToPg

GET {{BASE_URL}}?token={{TOKEN}}

###

POST {{BASE_URL}}?token={{TOKEN}}
Content-Type: application/json

{
    "sehir": "Diyarbakır",
    "sehir_kodu": 21,
    "nufus": 217500,
    "ilce": [
        {
        "ilce_ad": "çınar",
        "ilce_kod": "21750",
        "ilce_nufus": "75000"
    }, 
    {
        "ilce_ad": "merkez",
        "ilce_kod": "21750",
        "ilce_nufus": "75000"
    }]
}